# Generated by Django 5.0.6 on 2024-05-26 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='Link',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='status',
            old_name='active',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='status',
            name='inactive',
        ),
    ]
