# Generated by Django 5.0.6 on 2024-05-28 06:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='added_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
