# Generated by Django 5.0.6 on 2024-05-26 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_link_slider_link_rename_active_status_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name': 'Currency', 'verbose_name_plural': 'Currencies'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Status', 'verbose_name_plural': 'Statuses'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'SubCategory', 'verbose_name_plural': 'SubCategories'},
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='discription',
            new_name='description',
        ),
    ]
