# Generated by Django 5.0.6 on 2024-06-02 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_imagegallery_remove_product_image_cart_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='gallery_image',
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='Gallery')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
        migrations.DeleteModel(
            name='ImageGallery',
        ),
    ]
