# Generated by Django 5.0.6 on 2024-05-26 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_category_options_alter_currency_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='images',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='slider_image'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='images',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='Category_images'),
        ),
    ]
