# Generated by Django 5.0.6 on 2024-05-26 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_slider_images_alter_subcategory_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('new_price', models.CharField(max_length=50)),
                ('old_price', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('image', models.ImageField(blank=True, max_length=500, null=True, upload_to='product_images')),
                ('short_description', models.TextField()),
                ('long_description', models.TextField()),
                ('SubCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.subcategory')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.brand')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.tag')),
            ],
        ),
    ]
