# Generated by Django 5.0.6 on 2024-05-26 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='product_image/'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='images',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='slider_image/'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='images',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='category_images'),
        ),
    ]
