# Generated by Django 5.0.6 on 2024-05-27 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_image_alter_slider_images_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='sort_by',
            new_name='rank',
        ),
    ]
