# Generated by Django 5.0.6 on 2024-06-04 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customuser_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='sex',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='Gender',
        ),
    ]
